project_id = "bkyuxvschuwngtcdhsyg"

[functions.send-canvas-email]
verify_jwt = false

[functions.send-assessment-notification]
verify_jwt = false

[functions.sync-to-google-sheets]
verify_jwt = false