project_id = "bkyuxvschuwngtcdhsyg"

[functions.send-canvas-email]
verify_jwt = false

[functions.send-assessment-notification]
verify_jwt = false

[functions.sync-to-google-sheets]
verify_jwt = false

[functions.generate-business-insights]
verify_jwt = false

[functions.send-exec-summary-email]
verify_jwt = false

[functions.generate-activity-qr]
verify_jwt = false

[functions.cluster-bottleneck-inputs]
verify_jwt = false

[functions.generate-executive-pdf]
verify_jwt = false